### ISSUE TITLE
feat: add test for patient authorization rules

### ISSUE THREAD

**Issue by andreakreichgauer** [dot-base/fhir-server#182]
### 🚀 Feature Description
Test functionality of patient authorization introduced by #168 

### ✔ Goals
The following test cases should be covered for a Patient user:
- [x] POST on ` <url>/api/fhir/QuestionnaireResponse`,  `<url>/api/fhir/Observation`, `<url>/api/fhir/List`and `<url>/api/fhir/Procedure` result in 201, if subject matches patient's id
- [x] GET on `<url>/api/fhir/CarePlan?subject=<patient's-id>&_include=CarePlan:instantiates-careplan-reference&_include:iterate=PlanDefinition:definition-reference` results in 200 and returns all CarePlans for the patient ~~with according PlanDefinitions and Questionnaires~~
- [x] Test whether both requests above return a 403, if subject does not match patient's id
- [x] Test whether authorization still works, if the requests above are sent as transactions

Additional for all users:
- [x] GET on  ` <url>/api/fhir/Questionnaire`, ` <url>/api/fhir/ValueSet`, ` <url>/api/fhir/CodeSystem`, ` <url>/api/fhir/PlanDefinition` returns 200

**Comment by rti** [comment]
I removed

> with according PlanDefinitions and Questionnaires

from the acceptance criteria because this is not really part of the auth checks (reading of plan definitions and quetionnaires is checked in another test on its own) and would require quite a bit of code in the test.

**Comment by rti** [comment]
I changed the http error code from 401 to 403 in

> Test whether both requests above return a 403, if subject does not match patient's id

This is what the implementation returns and I also think this is the correct behaviour. 401 Unauth, 403 Forbidden
