### ISSUE TITLE
Share draft resources

### ISSUE THREAD

**Issue by andreakreichgauer** [dot-base/fhir-server#37]
### 🚀 Describe the Improvement
Currently, user can only access draft resource that were created by themselves.

### ✔ Goals
To complete this story, these things have to be done:
- [ ] add operation `$share-draft` 
- [ ] POST  on `<baseUrl>/api/fhir/$share-draft` needs a Parameter resource specifying the draft document to share (will possibly cover several resources/ids that need to be fetched) and the user to share it with

### 🧰 Possible Solution
* There are three levels of [extended operations](https://hapifhir.io/hapi-fhir/docs/server_plain/rest_operations_operations.html#server-level-operations): server-, type- and instance-level.
* Could either use server-level and state document id in Parameters resource or use instance-level and call the operation directly on `<baseUrl>/api/fhir/Procedure/<id>/$share-draft`

**Comment by mecklenburg** [comment]
Should be discussed of this is a desired functionality!

**Comment by andreakreichgauer** [comment]
This is outdated.
