### ISSUE TITLE
Increase default page size

### ISSUE THREAD

**Issue by andreakreichgauer** [dot-base/fhir-server#58]
### 🚀 Feature Description
If a request results in more than 20 resources the FHIR server returns 20 results per Bundle page and handles the rest via paging. This default size should be increased, since even standard requests will quickly exceed 20 results.

### ✔ Goals
- [ ] Increase default page size from 20 to 50.

### 🧰 Possible Solution
- Possible change a property in `application.yml`

**Comment by kanwarpreet25** [comment]
Hi @andreakreichgauer  , Please find above pull request for the same
